services:
  api:
    build: 
      context: ./requestlogger.api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  processor:
    build: 
      context: ./service-python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"